team-dbre/dbre_BE

- .gitignore
add .idea, .idea/, .idea/*
.gitignore
> [Delete] ./idea

- dbre_BE/settings.py
- dbre_BE/urls.py
- poetry.lock
- pyproject.toml
settings installed_apps에 rest_framework, drf_spectacular 추가 urls에 스웨거 추가
> ⚙️Conf : drf- spectacular 세팅

- README.md
- pyproject.toml
- term/views.py
개발환경 분리 후 mypy error 발생해서 
해결 후 공유위해 PR 합니다.
[🎸Chore] mypy <-> 환경분리
여기에 mypy error 해결방법 있슴둥
> Develop <- Feature/user

- .github/workflows/ci.yml
- docker-compose.yml
- poetry.lock
> [🎸Chore] redis

- payment/views.py
APIView 클래스에 serializer_class 속성을 추가
> 🚧WIP :APIView 클래스에 serializer_class 속성 추가

- dbre_BE/settings/prod.py
- nginx/conf.d/default.conf
endofday.store(임시) -> desub.kr
> [🚀Deploy] 도메인 변경

- payment/serializers.py
- payment/services/payment_service.py
- payment/views.py
- poetry.lock
> ✨Feat : 구독 취소시 취소사유 추가

- dbre_BE/urls.py
- poetry.lock
- user/serializers.py
- user/utils.py
- user/views.py
google 로그인 과정 간소화
GET /auth/google/login -> 이동 -> callback -> POST /auth/google/login
->
GET /auth/google/login -> 이동 -> callback
&&
google social login user 핸드폰 인증 후 저장 api 추가
> [🚧WIP] google login & google verify phone

- dbre_BE/urls.py
- plan/views.py
> ✨Feat : plan 기능 추가

- user/views.py
> [🎨Style] swagger tags

- user/utils.py
- user/views.py
POST /auth/google/login도 쿼리 파라미터로 환경 설정 해주시오...
> [🚧WIP] google social login

- dbre_BE/urls.py
- payment/serializers.py
- payment/views.py
payment views에 IsAuthenticated 추가
> ✨Feat : IsAuthenticated 추가

- user/serializers.py
- user/views.py
로그인은 인가이고, 토큰, 세션은 인증이니까 인증단계(후)에서 유저 정보를 넘겨주는게 맞다고 하심 그래서 로그인(인가) 단계에서 유저 정보를 넘기는 것은 옳지 않은것으로 사료됨.
> [🚧WIP] user ID

- dbre_BE/urls.py
- user/serializers.py
- user/views.py
> [✨Feat] find-email

- docker-compose.prod.yml
> [🚀Deploy] redis volume 설정 삭제

- Dockerfile
- docker-compose.prod.yml
> [🚀Deploy][🚑Hotfix] 정적파일 수집 중 오류 발생

- .gitignore
- Dockerfile
- docker-compose.prod.yml
> [🚀Deploy][🚑Hotfix] Django 설치 실패 문제

- payment/services/web_hook_service.py
- payment/views.py
> 🚧WIP : 포트원 웹훅 카드정보 발급

- dbre_BE/settings/base.py
- payment/apps.py
- payment/scheduler.py
- payment/services/payment_service.py
- poetry.lock
- pyproject.toml
장고 스케줄러 apscheduler 를 이용한 정기 결제 스케줄 기능 구현
> ✨Feat : 포트원 정기 결제를 위한 스케줄러 설치

- payment/views.py
> 🚑Hotfix : 빌링키 저장 후 응답 제거

- admin_api/serializers.py
- admin_api/views.py
- dbre_BE/urls.py
- poetry.lock
admin 페이지 구독 현황 기능 개발
구독상태 active, pause 만 조회
첫 구독일을 기준 오름차순 기본 정렬
구독 현황 대시보드(개발중)
> ✨Feat : admin 구독 현황 기능 구현

- payment/services/payment_service.py
> 🚑Hotfix : 남은 일수 초기화 제거

- plan/views.py
operationId 중복으로 swagger 에러 메세지 뜸
중복 operation_id 명확하게 지정
> 🚑Hotfix :  operationId 중복 문제 해결

- docker-compose.prod.yml
> [🚀Deploy] redis volumes 수정

- .github/workflows/ci-cd.yml
Docker 컨테이너 내에서 python manage.py check 명령을 실행할 때 Django를 찾지 못하는 문제 발생
Gunicorn은 WSGI 서버로서 Django 애플리케이션을 직접 실행하므로, manage.py를 통한 실행과는 다른 방식으로 작동
Django 의존성 체크를 건너뛰고, 컨테이너가 정상적으로 실행 확인
> [🚀Deploy] Django 의존성 문제 회피

- .github/workflows/ci-cd.yml
- Dockerfile
- docker-compose.prod.yml
> [🚀Deploy] 작전명 변경

- dbre_BE/urls.py
> [🚀Deploy] 하..

- dbre_BE/urls.py
이젠 진짜 될듯!
아니면 1번만 더하면 완료임 ㄹㅇ로!
> [🚀Deploy] 다시 돌아온 health check

- .github/workflows/ci-cd.yml
- docker-compose.prod.yml
cd에서 실행하는게 아닌
docker-compose.prod.yml에서 web을 실행할 때
gunicorn 실행 전 migrate 수행
> [🚀Deploy] migrate 순서 변경

- plan/views.py
> 🔨Refactor : 플랜 수정

- admin_api/serializers.py
> 🚑Hotfix : 객체 오류

- admin_api/serializers.py
- admin_api/views/user_views.py
> [📝Docs] 고객관리 page API Swagger 문서 정리

- admin_api/urls.py
- admin_api/views/subs_views.py
> ✨Feat : 결제 취소 모달 데이터

- admin_api/serializers.py
- admin_api/views/subs_views.py
serializers 추가
구독 취소 리스트 응답 subs_id 추가
> 🔨Refactor : 환불 승인 전 결제 정보 직렬화

- admin_api/serializers.py
- admin_api/views/user_views.py
> [🚧WIP] 정렬 쿼리 및 페이지네이션 비활성화

- dbre_BE/urls.py
- payment/serializers.py
- payment/views.py
프론트에서 빌링키 발급 모바일로 구현시 url 파라미터로 빌링키가 들어가는 문제가 생김
카드정보 입력 받아서 백엔드 자체 발급으로 보안성 강화
> ✨Feat : 모바일용 빌링키 발급 api 구현

- admin_api/serializers.py
- admin_api/views/admin_views.py
superuser 만이 관리자 비밀번호 변경이 가능한데, 바꿀 때 user_id를 받아서 관리자를 지정한 다음 비밀번호 변경하도록 변경. 기존에는 그냥 슈퍼유저의 비밀번호만 바꾸는 api였던 거임
> [🚧WIP] admin 비밀번호 변경

- payment/utils.py
> 🚑Hotfix : 구독 재개시 예약결제 안되는 상황 발생

- payment/serializers.py
> 🚑Hotfix : 카드변경사항 저장을 못함
